<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Inpatient extends CI_Controller {


	function __construct() {

		parent::__construct();

		$this->load->model('inpatient_model');
	
	}

	public function index()
	{
		
		$cityList = array('AUBURN','BATAVIA','BATH','BINGHAMTON','BROCKPORT','BUFFALO','CANANDAIGUA','CLIFTON SPRINGS','CORNING','CORTLAND','DANSVILLE','ELMIRA','GENEVA','GOWANDA','HORNELL','ITHACA','JAMESTOWN','JOHNSON CITY','KENMORE','LEWISTON','LOCKPORT','MEDINA', 'NEWARK', 'NIAGARA FALLS','OLEAN','OSWEGO','ROCHESTER','SPRINGVILLE','SYRACUSE','UTICA','WARSAW','WATERTOWN','WELLSVILLE');


		//$cityList = array('AUBURN', 'ROCHESTER');

		//$codeList = array('039','057','064','065','066','069','074','101','176','177','178','189','190','191','192','193','194','195','202','207','208','238','243','244','246','247','249','251','252','253','254','280','281','282','286','287','291','292','293','300','301','303','308','309','310','312','313','314','315','329','330','372','377','378','389','390','391','392','394','418','419','460','469','470','473','480','481','491','552','602','603','638','640','641','682','683','684','689','690','698','699','811','812','853','870','871','872','885','897','917','918','948','439','203','379','563','482','536','305','149');

		$codeList = array('101');

		//$codeList = array('039 - EXTRACRANIAL PROCEDURES W/O CC/MCC','057 - DEGENERATIVE NERVOUS SYSTEM DISORDERS W/O MCC','064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W MCC','065 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W CC','066 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W/O CC/MCC','069 - TRANSIENT ISCHEMIA','074 - CRANIAL & PERIPHERAL NERVE DISORDERS W/O MCC','101 - SEIZURES W/O MCC','176 - PULMONARY EMBOLISM W/O MCC','177 - RESPIRATORY INFECTIONS & INFLAMMATIONS W MCC','178 - RESPIRATORY INFECTIONS & INFLAMMATIONS W CC','189 - PULMONARY EDEMA & RESPIRATORY FAILURE','190 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W MCC','191 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W CC','192 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W/O CC/MCC','193 - SIMPLE PNEUMONIA & PLEURISY W MCC','194 - SIMPLE PNEUMONIA & PLEURISY W CC','195 - SIMPLE PNEUMONIA & PLEURISY W/O CC/MCC','202 - BRONCHITIS & ASTHMA W CC/MCC','207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS','208 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT <96 HOURS','238 - MAJOR CARDIOVASC PROCEDURES W/O MCC','243 - PERMANENT CARDIAC PACEMAKER IMPLANT W CC','244 - PERMANENT CARDIAC PACEMAKER IMPLANT W/O CC/MCC','246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS','247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC','249 - PERC CARDIOVASC PROC W NON-DRUG-ELUTING STENT W/O MCC','251 - PERC CARDIOVASC PROC W/O CORONARY ARTERY STENT W/O MCC','252 - OTHER VASCULAR PROCEDURES W MCC','253 - OTHER VASCULAR PROCEDURES W CC','254 - OTHER VASCULAR PROCEDURES W/O CC/MCC','280 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W MCC','281 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W CC','282 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W/O CC/MCC','286 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W MCC','287 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W/O MCC','291 - HEART FAILURE & SHOCK W MCC','292 - HEART FAILURE & SHOCK W CC','293 - HEART FAILURE & SHOCK W/O CC/MCC','300 - PERIPHERAL VASCULAR DISORDERS W CC','301 - PERIPHERAL VASCULAR DISORDERS W/O CC/MCC','303 - ATHEROSCLEROSIS W/O MCC','308 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W MCC','309 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W CC','310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W/O CC/MCC','312 - SYNCOPE & COLLAPSE','313 - CHEST PAIN','314 - OTHER CIRCULATORY SYSTEM DIAGNOSES W MCC','315 - OTHER CIRCULATORY SYSTEM DIAGNOSES W CC','329 - MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC','330 - MAJOR SMALL & LARGE BOWEL PROCEDURES W CC','372 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W CC','377 - G.I. HEMORRHAGE W MCC','378 - G.I. HEMORRHAGE W CC','389 - G.I. OBSTRUCTION W CC','390 - G.I. OBSTRUCTION W/O CC/MCC','391 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W MCC','392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W/O MCC','394 - OTHER DIGESTIVE SYSTEM DIAGNOSES W CC','418 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W CC','419 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W/O CC/MCC','460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC','469 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W MCC','470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC','473 - CERVICAL SPINAL FUSION W/O CC/MCC','480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC','481 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W CC','491 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC','552 - MEDICAL BACK PROBLEMS W/O MCC','602 - CELLULITIS W MCC','603 - CELLULITIS W/O MCC','638 - DIABETES W CC','640 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W MCC','641 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W/O MCC','682 - RENAL FAILURE W MCC','683 - RENAL FAILURE W CC','684 - RENAL FAILURE W/O CC/MCC','689 - KIDNEY & URINARY TRACT INFECTIONS W MCC','690 - KIDNEY & URINARY TRACT INFECTIONS W/O MCC','698 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W MCC','699 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W CC','811 - RED BLOOD CELL DISORDERS W MCC','812 - RED BLOOD CELL DISORDERS W/O MCC','853 - INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC','870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS','871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W MCC','872 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W/O MCC','885 - PSYCHOSES','897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC','917 - POISONING & TOXIC EFFECTS OF DRUGS W MCC','918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC','948 - SIGNS & SYMPTOMS W/O MCC','439 - DISORDERS OF PANCREAS EXCEPT MALIGNANCY W CC','203 - BRONCHITIS & ASTHMA W/O CC/MCC','379 - G.I. HEMORRHAGE W/O CC/MCC','563 - FX, SPRN, STRN & DISL EXCEPT FEMUR, HIP, PELVIS & THIGH W/O MCC','482 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC','536 - FRACTURES OF HIP & PELVIS W/O MCC','305 - HYPERTENSION W/O MCC','149 - DYSEQUILIBRIU');

		/*$codeList = array(
			'069 - TRANSIENT ISCHEMIA',
			'101 - SEIZURES W/O MCC',
			'176 - PULMONARY EMBOLISM W/O MCC',
			'189 - PULMONARY EDEMA & RESPIRATORY FAILURE',
			'190 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W MCC',
			'193 - SIMPLE PNEUMONIA & PLEURISY W MCC',
			'202 - BRONCHITIS & ASTHMA W CC/MCC',
			'238 - MAJOR CARDIOVASC PROCEDURES W/O MCC',
			'243 - PERMANENT CARDIAC PACEMAKER IMPLANT W CC',
			'291 - HEART FAILURE & SHOCK W MCC',
			'300 - PERIPHERAL VASCULAR DISORDERS W CC',
			'303 - ATHEROSCLEROSIS W/O MCC',
			'308 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W MCC',
			'312 - SYNCOPE & COLLAPSE',
			'313 - CHEST PAIN',
			'460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC',
			'473 - CERVICAL SPINAL FUSION W/O CC/MCC',
			'480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC',
			'491 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC',
			'552 - MEDICAL BACK PROBLEMS W/O MCC',
			'602 - CELLULITIS W MCC',
			'638 - DIABETES W CC',
			'682 - RENAL FAILURE W MCC',
			'689 - KIDNEY & URINARY TRACT INFECTIONS W MCC',
			'897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC');
*/
		//$data['cities'] = $cityList;
		$DRDbyProviderbyCity = array();

		foreach($cityList as $city){
			$cityProviders = $this->inpatient_model->query_city($city);
			foreach($cityProviders as $cityProvider) {
				//array_push($DRDbyProviderbyCity, $cityProvider['Provider_Id']);
				$providerID = $cityProvider['Provider_Id'];
				foreach($codeList as $code) {
					//$DRD = $codeList[0];
					$DRD = $code;
					$var = $this->inpatient_model->query_drd($providerID, $DRD);
					// if provider has drd code associated with it
					if(count($var) != 0){
						array_push($DRDbyProviderbyCity, $var);
					}
				}
			}
		}

		$data['test'] = $DRDbyProviderbyCity;

		$this->load->view('inpatient_view', $data);

	}

	public function query_data() {

		//$DRD = '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC';

		$DRD = $this->input->post('id');

		$cityList = array('AUBURN','BATAVIA','BATH','BINGHAMTON','BROCKPORT','BUFFALO','CANANDAIGUA','CLIFTON SPRINGS','CORNING','CORTLAND','DANSVILLE','ELMIRA','GENEVA','GOWANDA','HORNELL','ITHACA','JAMESTOWN','JOHNSON CITY','KENMORE','LEWISTON','LOCKPORT','MEDINA','NEWARK', 'NIAGARA FALLS', 'OLEAN','OSWEGO','ROCHESTER','SPRINGVILLE','SYRACUSE','UTICA','WARSAW','WATERTOWN','WELLSVILLE');

		$DRDbyProviderbyCity = array();

		foreach($cityList as $city){
			$cityProviders = $this->inpatient_model->query_city($city);
			foreach($cityProviders as $cityProvider) {
				//array_push($DRDbyProviderbyCity, $cityProvider['Provider_Id']);
				$providerID = $cityProvider['Provider_Id'];
				$var = $this->inpatient_model->query_drd($providerID, $DRD);
				// if provider has drd code associated with it
				if(count($var) != 0){
					array_push($DRDbyProviderbyCity, $var);
				}
			}
		}

		$data['test'] = $DRDbyProviderbyCity;

		$this->load->view('results_view', $data);

	}

	public function update() {

		$entries = $this->inpatient_model->fetch_all();

		foreach($entries as $entry){
			//echo substr($entry['DRD_Definition'],0,3);
			$this->inpatient_model->update_drd($entry['Id'],substr($entry['DRD_Definition'],0,3));
		}

	}

}

/* End of file inpatient.php */
/* Location: ./application/controllers/inpatient.php */